# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_SECURITY_DLPACK) := dlpack.o
ccflags-$(CONFIG_SECURITY_DLPACK) := -std=gnu11

dlpack-y := dlpack.o hash.o event.o action.o state.o trans.o fsm.o right_abs.o pattern.o securityfs.o file_check.o policy_interface.o
